#if UNITY_EDITOR && !DREAMPARKCORE
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using UnityEditor;
using UnityEngine;

namespace DreamPark
{
    // Auto-generates a `link.xml` for a content title that preserves every
    // MonoBehaviour / ScriptableObject / StateMachineBehaviour declared in
    // Assets/Content/{contentId}/.
    //
    // The problem this solves
    // -----------------------
    // dreampark-core ships a player binary (Quest / iOS) that gets built via
    // IL2CPP. IL2CPP runs a managed-stripping pass that removes types it
    // determines are unreferenced. The analyzer looks at:
    //   - Direct code references (foo.GetComponent<MyBehaviour>())
    //   - Serialized references inside assets that ship with the build
    //
    // But the analyzer does NOT see references hiding inside addressable
    // content bundles (those are loaded at runtime from the CDN). So if a
    // content title has `MyEnemyAI : MonoBehaviour` that's only ever attached
    // to prefabs inside the content's addressable bundles, IL2CPP strips it
    // from the player binary. When the bundle later tries to deserialize
    // a prefab with that component, Unity throws:
    //
    //     Could not produce class with ID <stableTypeHash>.
    //     This could be caused by a class being stripped from the build...
    //
    // The fix is `link.xml`, which tells IL2CPP "preserve these types
    // regardless of static analysis."
    //
    // Why generate per-content
    // ------------------------
    // A single hand-maintained link.xml in dreampark-core can't keep up:
    // every time a creator adds a new MonoBehaviour or ScriptableObject to
    // their content, someone has to remember to also touch link.xml. Miss
    // one and you get a stripping bug in production months later, only
    // hitting players who navigate into the affected content.
    //
    // By generating link.xml on the SDK side at unitypackage-build time,
    // every content release ships its OWN preservation rules. When dreampark-
    // core imports the unitypackage, link.xml lands at
    //     Assets/Content/{contentId}/link.xml
    // and Unity's build system picks up every link.xml anywhere under Assets/
    // automatically. The system is self-maintaining: any new type a creator
    // adds is automatically preserved on the next upload.
    //
    // What gets preserved
    // -------------------
    // Only the three categories of types Unity instantiates from serialized
    // data:
    //   - MonoBehaviour (and subclasses): attached to prefabs, scenes
    //   - ScriptableObject (and subclasses): asset-based configuration
    //   - StateMachineBehaviour: Animator state behaviors
    //
    // Other classes (pure data types, [Serializable] structs used as fields,
    // utility classes) get pulled in via the IL2CPP linker's transitive
    // analysis from the types we DO preserve. No need to enumerate them.
    //
    // Skipped
    // -------
    //   - Editor-only scripts (under any /Editor/ folder): they don't ship
    //     to the player at all, so stripping is irrelevant.
    //   - Generic type definitions (MyBehaviour<T>): each closed generic is
    //     a separate type to IL2CPP and we can't enumerate them without
    //     knowing usage. Document this limit; if a creator hits it, they
    //     can hand-extend the generated file.
    public static class ContentLinkXmlGenerator
    {
        private const string GeneratedHeader =
            "<!-- AUTO-GENERATED by DreamPark SDK during BuildUnityPackage. Do not edit by hand. -->";

        // Generates Assets/Content/{contentId}/link.xml. Idempotent — skips
        // the write when the resulting content matches what's already on
        // disk, so calling this on every upload doesn't dirty git or
        // trigger unnecessary AssetDatabase reimports.
        //
        // Returns the relative asset path of the generated link.xml so
        // callers (BuildUnityPackage) can include it in the ExportPackage
        // call. Returns null if no preservable types were found (and any
        // stale link.xml has been cleaned up).
        public static string GenerateForContent(string contentId)
        {
            if (string.IsNullOrEmpty(contentId)) return null;
            string contentRoot = "Assets/Content/" + contentId;
            if (!AssetDatabase.IsValidFolder(contentRoot)) return null;
            string linkXmlPath = contentRoot + "/link.xml";

            // Collect every preservable type declared in the content folder.
            // Group by assembly so the emitted XML is compact.
            var typesByAssembly = new SortedDictionary<string, SortedSet<string>>(StringComparer.Ordinal);

            string[] scriptGuids = AssetDatabase.FindAssets("t:MonoScript", new[] { contentRoot });
            foreach (var guid in scriptGuids)
            {
                string path = AssetDatabase.GUIDToAssetPath(guid);
                if (string.IsNullOrEmpty(path)) continue;
                if (path.IndexOf("/Editor/", StringComparison.OrdinalIgnoreCase) >= 0) continue;

                var monoScript = AssetDatabase.LoadAssetAtPath<MonoScript>(path);
                if (monoScript == null) continue;

                Type type;
                try { type = monoScript.GetClass(); }
                catch { continue; }
                if (type == null) continue;

                if (!IsPreservableType(type)) continue;
                if (type.IsGenericTypeDefinition || type.IsGenericType) continue;

                string asmName = type.Assembly?.GetName()?.Name;
                if (string.IsNullOrEmpty(asmName)) continue;

                string typeName = type.FullName;
                if (string.IsNullOrEmpty(typeName)) continue;

                if (!typesByAssembly.TryGetValue(asmName, out var set))
                {
                    set = new SortedSet<string>(StringComparer.Ordinal);
                    typesByAssembly[asmName] = set;
                }
                set.Add(typeName);
            }

            // No preservable types → no link.xml. Clean up any stale file
            // from a prior build so the unitypackage doesn't ship an
            // outdated preservation list.
            if (typesByAssembly.Count == 0)
            {
                if (File.Exists(ToFullPath(linkXmlPath)))
                {
                    AssetDatabase.DeleteAsset(linkXmlPath);
                    Debug.Log($"[ContentLinkXmlGenerator] No preservable types under {contentRoot} — removed stale link.xml.");
                }
                return null;
            }

            string newContent = BuildXml(contentId, typesByAssembly);

            // Idempotent write: skip if content already matches on disk.
            string fullPath = ToFullPath(linkXmlPath);
            if (File.Exists(fullPath))
            {
                try
                {
                    string existing = File.ReadAllText(fullPath);
                    if (existing == newContent) return linkXmlPath;
                }
                catch { /* fall through to write */ }
            }

            try
            {
                File.WriteAllText(fullPath, newContent);
                AssetDatabase.ImportAsset(linkXmlPath, ImportAssetOptions.ForceUpdate);

                int totalTypes = typesByAssembly.Sum(kv => kv.Value.Count);
                int asmCount = typesByAssembly.Count;
                Debug.Log($"[ContentLinkXmlGenerator] Wrote {linkXmlPath} — preserves {totalTypes} type{(totalTypes == 1 ? "" : "s")} across {asmCount} assembl{(asmCount == 1 ? "y" : "ies")}.");
                return linkXmlPath;
            }
            catch (Exception e)
            {
                Debug.LogError($"[ContentLinkXmlGenerator] Failed to write {linkXmlPath}: {e}");
                return null;
            }
        }

        // True when the type is one IL2CPP would strip but Unity tries to
        // instantiate at runtime from serialized data. Catches inheritance
        // — `MyEnemyAI : EnemyAI : MonoBehaviour` still returns true.
        private static bool IsPreservableType(Type type)
        {
            return typeof(MonoBehaviour).IsAssignableFrom(type)
                || typeof(ScriptableObject).IsAssignableFrom(type)
                || typeof(StateMachineBehaviour).IsAssignableFrom(type);
        }

        private static string BuildXml(string contentId, SortedDictionary<string, SortedSet<string>> typesByAssembly)
        {
            var sb = new StringBuilder();
            sb.AppendLine("<linker>");
            sb.AppendLine("    " + GeneratedHeader);
            sb.AppendLine($"    <!-- Content title: {contentId} -->");
            sb.AppendLine();
            sb.AppendLine("    <!-- Preserves every MonoBehaviour / ScriptableObject /");
            sb.AppendLine("         StateMachineBehaviour declared in this content title so");
            sb.AppendLine("         IL2CPP doesn't strip types that are referenced only by");
            sb.AppendLine("         addressable bundle serialization (not by code in the player");
            sb.AppendLine("         binary's own scenes / assets). Without this, attempting to");
            sb.AppendLine("         deserialize a stripped type at runtime throws \"Could not");
            sb.AppendLine("         produce class with ID X\". -->");
            foreach (var kv in typesByAssembly)
            {
                sb.AppendLine();
                sb.AppendLine($"    <assembly fullname=\"{kv.Key}\">");
                foreach (var typeName in kv.Value)
                {
                    sb.AppendLine($"        <type fullname=\"{XmlEscape(typeName)}\" preserve=\"all\"/>");
                }
                sb.AppendLine("    </assembly>");
            }
            sb.AppendLine("</linker>");
            return sb.ToString();
        }

        private static string XmlEscape(string s)
        {
            // Type names with generic parameters can contain angle brackets;
            // also defensive against ampersands. Quotes don't appear in
            // valid C# type names so we leave those alone.
            return s
                .Replace("&", "&amp;")
                .Replace("<", "&lt;")
                .Replace(">", "&gt;");
        }

        private static string ToFullPath(string assetPath)
        {
            string projectRoot = Path.GetFullPath(Path.Combine(Application.dataPath, ".."));
            return Path.Combine(projectRoot, assetPath);
        }
    }
}
#endif
